version: '2'
services:
    tasksappmongo-app:
        image: tasksappmongo
        environment:
        # - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - SPRING_PROFILES_ACTIVE=prod,swagger
        - SPRING_DATA_MONGODB_URI=mongodb://tasksappmongo-mongodb:27017
        - SPRING_DATA_MONGODB_DATABASE=TasksAppMongo
        - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
        - 8080:8080
    tasksappmongo-mongodb:
        extends:
            file: mongodb.yml
            service: tasksappmongo-mongodb
