version: '2'
services:
    tasksappmongo-mongodb:
        image: mongo:3.6.3
        ports:
        - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/TasksAppMongo/mongodb/:/data/db/
